apiVersion: v1
kind: ConfigMap
metadata:
  name: strongdm-gateway-config
  namespace: strongdm-system
  labels:
    app.kubernetes.io/name: strongdm-gateway
    app.kubernetes.io/instance: {{ .Values.environment }}
data:
  # strongDM Gateway Configuration
  SDM_DOCKERIZED: "true"
  SDM_RELAY_LOG_LEVEL: "info"
  
  # Cluster-specific configuration
  CLUSTER_NAME: "{{ .Values.cluster_name }}"
  CLUSTER_REGION: "{{ .Values.region }}"
  ENVIRONMENT: "{{ .Values.environment }}"
  
  # Network configuration for EKS private access
  {{- if .Values.strongdm.cluster_endpoint }}
  CLUSTER_ENDPOINT: "{{ .Values.strongdm.cluster_endpoint }}"
  {{- end }}
  
  # Additional strongDM configuration
  SDM_LISTEN_ADDRESS: "0.0.0.0:5432"
  SDM_RELAY_BIND_ADDRESS: "0.0.0.0"

