{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.gatewayToken.name }}
  namespace: strongdm-system
  labels:
    app.kubernetes.io/name: strongdm-gateway
    app.kubernetes.io/instance: {{ .Values.environment | default "default" }}
    app.kubernetes.io/component: security
spec:
  refreshInterval: {{ .Values.externalSecrets.gatewayToken.refreshInterval | default "5m" }}
  
  # Use the same External Secrets service account as the external-secrets addon
  secretStoreRef:
    name: aws-secretsmanager-secret-store
    kind: ClusterSecretStore
  
  # Target Kubernetes secret that strongDM chart will use
  target:
    name: {{ .Values.externalSecrets.gatewayToken.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # strongDM token from AWS Secrets Manager
        token: "{{ "{{ .token }}" }}"
        
  # Pull strongDM gateway token from AWS Secrets Manager
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.externalSecrets.gatewayToken.provider.aws.secretName | quote }}
      property: {{ .Values.externalSecrets.gatewayToken.provider.aws.key | default "gateway-token" }}
{{- end }}

