# strongDM Token Secrets
# These should be created manually in the strongDM admin console and applied here
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.strongdm.admin_token_secret }}
  namespace: strongdm-system
  labels:
    app.kubernetes.io/name: strongdm-gateway
    app.kubernetes.io/instance: {{ .Values.environment }}
  annotations:
    # This secret should be populated manually with values from strongDM admin console
    strongdm.com/token-type: "admin"
type: Opaque
data:
  # Base64 encoded values - to be populated during setup
  # SDM_ADMIN_TOKEN: <base64-encoded-admin-token>
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.strongdm.relay_token_secret }}
  namespace: strongdm-system
  labels:
    app.kubernetes.io/name: strongdm-gateway
    app.kubernetes.io/instance: {{ .Values.environment }}
  annotations:
    strongdm.com/token-type: "relay"
type: Opaque
data:
  # Base64 encoded values - to be populated during setup
  # SDM_RELAY_TOKEN: <base64-encoded-relay-token>
  token: ""

