apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    environment: {{ .Values.environment }}
  annotations:
    {{- if .Values.linkerd.inject }}
    linkerd.io/inject: enabled
    {{- end }}

