{{- if .Values.certificates.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  labels:
    {{- include "linkerd-control-plane.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: linkerd-identity-issuer
    type: kubernetes.io/tls
    template:
      engineVersion: v2
      data:
        tls.crt: "{{ `{{ .certificate }}` }}"
        tls.key: "{{ `{{ .privateKey }}` }}"
  data:
    - secretKey: certificate
      remoteRef:
        key: {{ .Values.certificates.externalSecrets.secretName }}
        property: certificate
    - secretKey: privateKey
      remoteRef:
        key: {{ .Values.certificates.externalSecrets.secretName }}
        property: privateKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    {{- include "linkerd-control-plane.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: linkerd-identity-trust-roots-secret
    type: Opaque
    template:
      engineVersion: v2
      data:
        ca-bundle.crt: "{{ `{{ .trustAnchor }}` }}"
  data:
    - secretKey: trustAnchor
      remoteRef:
        key: {{ .Values.certificates.externalSecrets.secretName }}
        property: trustAnchor
{{- end }}