# Linkerd Control Plane - Staging Environment

# High availability for staging
controllerReplicas: 2

# Override default automatic certificates with External Secrets
identity:
  issuer:
    scheme: kubernetes.io/tls  # Use manual certificate management

# Use External Secrets for certificate management
certificates:
  externalSecrets:
    enabled: true
    secretName: "linkerd-certificates-staging"
  bootstrap:
    enabled: true  # Enable certificate bootstrap for staging
  rotation:
    enabled: true  # Enable certificate rotation for staging

# Production-like resources for staging
resources:
  cpu:
    limit: 1
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi

# Proxy sidecar resources for staging
proxy:
  resources:
    cpu:
      limit: 1
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi

# Security policy for staging (more restrictive)
policyController:
  defaultPolicy: "deny"

