# Linkerd Control Plane - Production Environment

# High availability for production
controllerReplicas: 3

# Use External Secrets for certificate management
certificates:
  externalSecrets:
    enabled: true
    secretName: "linkerd-certificates-prod"
  bootstrap:
    enabled: true  # Enable certificate bootstrap for production
  rotation:
    enabled: true  # Enable certificate rotation for production

# Full production resources
resources:
  cpu:
    limit: 2
    request: 200m
  memory:
    limit: 512Mi
    request: 100Mi

# Proxy sidecar resources for production
proxy:
  resources:
    cpu:
      limit: 2
      request: 100m
    memory:
      limit: 512Mi
      request: 32Mi

# Strict security policy for production
policyController:
  defaultPolicy: "deny"

# Production certificate management with cert-manager
identity:
  issuer:
    scheme: linkerd.io/tls  # Use Linkerd's issuer with cert-manager
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s
  
  # Production-grade certificate configuration
  # These should be managed via cert-manager ClusterIssuer
  trustAnchorsPEM: |
    # Root CA certificate from your organization's PKI
    # This should be provided by your certificate management team

# Enhanced monitoring for production
# Additional scrape configs for detailed metrics
prometheus:
  scrapeConfigs:
    - job_name: 'linkerd-controller'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['linkerd', 'linkerd-viz']
