# Linkerd Test App - Default Configuration
# This file provides default values that can be overridden by environment-specific configs

environment: default
region: us-west-2
cluster_name: ""

# Default application configuration
app:
  name: linkerd-test-app
  namespace: linkerd-test

# Frontend service defaults
frontend:
  name: frontend
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

# Backend service defaults
backend:
  name: backend
  replicaCount: 2
  image:
    repository: httpbin/httpbin
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 80
  
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

# Linkerd configuration
linkerd:
  inject: true
  trafficSplit:
    enabled: false

# Load testing defaults
loadTest:
  enabled: true
  image:
    repository: curlimages/curl
    tag: "8.5.0"
  
  requests: 10
  concurrency: 2
