apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkerd-test-app.name" . }}-backend
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "linkerd-test-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "linkerd-test-app.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "linkerd-test-app.backend.selectorLabels" . | nindent 8 }}
        {{- include "linkerd-test-app.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.linkerd.inject }}
        linkerd.io/inject: enabled
        {{- end }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
        env:
        - name: SERVICE_NAME
          value: "backend"
        - name: ENVIRONMENT  
          value: {{ .Values.environment }}
        - name: REGION
          value: {{ .Values.region }}
