apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkerd-test-app.name" . }}-backend
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "linkerd-test-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "linkerd-test-app.backend.selectorLabels" . | nindent 4 }}
