apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkerd-test-app.name" . }}-frontend
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "linkerd-test-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "linkerd-test-app.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "linkerd-test-app.frontend.selectorLabels" . | nindent 8 }}
        {{- include "linkerd-test-app.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.linkerd.inject }}
        linkerd.io/inject: enabled
        {{- end }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
        env:
        - name: SERVICE_NAME
          value: "frontend"
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        - name: REGION
          value: {{ .Values.region }}
        - name: BACKEND_URL
          value: "http://{{ include "linkerd-test-app.name" . }}-backend:{{ .Values.backend.service.port }}"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: html-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "linkerd-test-app.name" . }}-frontend-config
      - name: html-content
        configMap:
          name: {{ include "linkerd-test-app.name" . }}-frontend-config
