apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespace }}
  labels:
    {{- include "linkerd-test-app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.linkerd.inject }}
    linkerd.io/inject: enabled
    {{- end }}
spec:
