# Linkerd Control Plane Default Configuration

# Use external secret management for security
identity:
  issuer:
    scheme: kubernetes.io/tls  # Reference external secret
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s

# AWS configuration (will be provided by ApplicationSet)
aws:
  region: ""  # Will be set by ApplicationSet

# Environment (will be provided by ApplicationSet)
environment: ""  # Will be set by ApplicationSet

# High availability configuration
controllerReplicas: 1  # Will be overridden in staging/prod

# Resource configuration
resources:
  cpu:
    limit: 1
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi

# Proxy configuration
proxy:
  resources:
    cpu:
      limit: 1
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi

# Enable default policy mode (recommended for security)
policyController:
  defaultPolicy: "deny"

# cert-manager integration (disabled by default)
certManager:
  enabled: false
  # For production environments, provide your organization's root CA
  trustAnchor: ""     # Root CA certificate (PEM format)
  trustAnchorKey: ""  # Root CA private key (PEM format)

# Observability integration
# These will integrate with your existing Prometheus/Grafana
prometheusUrl: ""  # Set by ApplicationSet
grafanaUrl: ""     # Set by ApplicationSet

# Debug configuration for development
debugContainer:
  image:
    name: cr.l5d.io/linkerd/debug
    pullPolicy: Always
