# Linkerd Control Plane Default Configuration

# Identity and certificates - External Secrets configuration for production
identity:
  issuer:
    scheme: kubernetes.io/tls
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s

# Certificate management via External Secrets
certificates:
  externalSecrets:
    enabled: true  # Enable for production environments
    secretName: "linkerd-certificates"  # AWS Secrets Manager secret name

  # Bootstrap job to create initial certificates
  bootstrap:
    enabled: true  # Will check if certificates exist before creating
    version: "v1"  # Increment to force regeneration

  # Automated certificate rotation
  rotation:
    enabled: true  # Enable monthly certificate rotation
    serviceAccount:
      roleArn: ""  # Will be set by ApplicationSet from cluster metadata

# AWS configuration (will be provided by ApplicationSet)
aws:
  region: ""  # Will be set by ApplicationSet

# Environment (will be provided by ApplicationSet)
environment: ""  # Will be set by ApplicationSet

# High availability configuration
controllerReplicas: 1  # Will be overridden in staging/prod

# Resource configuration
resources:
  cpu:
    limit: 1
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi

# Proxy configuration
proxy:
  resources:
    cpu:
      limit: 1
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi

# Enable default policy mode (recommended for security)
policyController:
  defaultPolicy: "deny"

# cert-manager integration (disabled by default)
certManager:
  enabled: false
  # For production environments, provide your organization's root CA
  trustAnchor: ""     # Root CA certificate (PEM format)
  trustAnchorKey: ""  # Root CA private key (PEM format)

# Observability integration
# These will integrate with your existing Prometheus/Grafana
prometheusUrl: ""  # Set by ApplicationSet
grafanaUrl: ""     # Set by ApplicationSet

# Debug configuration for development
debugContainer:
  image:
    name: cr.l5d.io/linkerd/debug
    pullPolicy: Always
