# Linkerd Control Plane Default Configuration

# Identity and certificates - Built-in automatic generation
identity:
  issuer:
    # Use Linkerd's built-in automatic certificate generation (default)
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s

# High availability configuration
controllerReplicas: 1  # Will be overridden in staging/prod

# Resource configuration
resources:
  cpu:
    limit: 1
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi

# Proxy configuration
proxy:
  resources:
    cpu:
      limit: 1
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi

# Enable default policy mode (recommended for security)
policyController:
  defaultPolicy: "deny"

# cert-manager integration (disabled by default)
certManager:
  enabled: false
  # For production environments, provide your organization's root CA
  trustAnchor: ""     # Root CA certificate (PEM format)
  trustAnchorKey: ""  # Root CA private key (PEM format)

# Observability integration
# These will integrate with your existing Prometheus/Grafana
prometheusUrl: ""  # Set by ApplicationSet
grafanaUrl: ""     # Set by ApplicationSet

# Debug configuration for development
debugContainer:
  image:
    name: cr.l5d.io/linkerd/debug
    pullPolicy: Always
