# Linkerd cert-manager Integration Template
# This file shows how to integrate Linkerd with cert-manager for production certificate management

{{- if .Values.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-identity-issuer
  labels:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/component: cert-manager
spec:
  ca:
    # Reference to the root CA secret managed by cert-manager
    secretName: linkerd-identity-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  labels:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/component: cert-manager
spec:
  # Identity issuer certificate
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-identity-issuer
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-identity-trust-anchor
  namespace: linkerd
  labels:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/component: cert-manager
type: Opaque
data:
  # This should contain your organization's root CA
  # Replace with actual root CA certificate (base64 encoded)
  tls.crt: {{ .Values.certManager.trustAnchor | b64enc }}
  tls.key: {{ .Values.certManager.trustAnchorKey | b64enc }}
{{- end }}
