# strongDM Gateway - Production Environment Overrides

# Production-specific configuration
environment: prod

# Configuration for official sdm-relay chart
sdm-relay:
  # Gateway/Relay configuration for production environment
  relay:
    name: "eks-gateway-prod"
    advertisedHost: ""  # Auto-configured by LoadBalancer
    advertisedPort: 5432
    
  # High availability with 3 replicas for production
  replicaCount: 3
  
  # Full production resources
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m" 
    limits:
      memory: "512Mi"
      cpu: "400m"
      
  # Enhanced security for production
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]

# External Secrets configuration for production environment
externalSecrets:
  enabled: true
  gatewayToken:
    provider:
      aws:
        region: "us-west-2"
        secretName: "strongdm-gateway-tokens-prod"
        key: "gateway-token"
